/**
 *
 *  Committee.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Committee.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::icnari_conference_db;

const std::string Committee::Cols::_id = "id";
const std::string Committee::Cols::_name = "name";
const std::string Committee::Cols::_specialization = "specialization";
const std::string Committee::Cols::_college = "college";
const std::string Committee::Cols::_committee = "committee";
const std::string Committee::Cols::_profile_picture_object_key = "profile_picture_object_key";
const std::string Committee::Cols::_position = "position";
const std::string Committee::Cols::_description = "description";
const std::string Committee::Cols::_priority = "priority";
const std::string Committee::primaryKeyName = "id";
const bool Committee::hasPrimaryKey = true;
const std::string Committee::tableName = "committee";

const std::vector<typename Committee::MetaData> Committee::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"name","std::string","character varying",255,0,0,1},
{"specialization","std::string","character varying",255,0,0,0},
{"college","std::string","character varying",255,0,0,0},
{"committee","std::string","character varying",32,0,0,1},
{"profile_picture_object_key","std::string","character varying",255,0,0,0},
{"position","std::string","character varying",255,0,0,0},
{"description","std::string","text",0,0,0,0},
{"priority","int32_t","integer",4,0,0,0}
};
const std::string &Committee::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Committee::Committee(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["specialization"].isNull())
        {
            specialization_=std::make_shared<std::string>(r["specialization"].as<std::string>());
        }
        if(!r["college"].isNull())
        {
            college_=std::make_shared<std::string>(r["college"].as<std::string>());
        }
        if(!r["committee"].isNull())
        {
            committee_=std::make_shared<std::string>(r["committee"].as<std::string>());
        }
        if(!r["profile_picture_object_key"].isNull())
        {
            profilePictureObjectKey_=std::make_shared<std::string>(r["profile_picture_object_key"].as<std::string>());
        }
        if(!r["position"].isNull())
        {
            position_=std::make_shared<std::string>(r["position"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["priority"].isNull())
        {
            priority_=std::make_shared<int32_t>(r["priority"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            specialization_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            college_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            committee_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            profilePictureObjectKey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            position_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            priority_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Committee::Committee(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            specialization_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            college_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            committee_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            profilePictureObjectKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            position_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            priority_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
}

Committee::Committee(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("specialization"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["specialization"].isNull())
        {
            specialization_=std::make_shared<std::string>(pJson["specialization"].asString());
        }
    }
    if(pJson.isMember("college"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["college"].isNull())
        {
            college_=std::make_shared<std::string>(pJson["college"].asString());
        }
    }
    if(pJson.isMember("committee"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["committee"].isNull())
        {
            committee_=std::make_shared<std::string>(pJson["committee"].asString());
        }
    }
    if(pJson.isMember("profile_picture_object_key"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["profile_picture_object_key"].isNull())
        {
            profilePictureObjectKey_=std::make_shared<std::string>(pJson["profile_picture_object_key"].asString());
        }
    }
    if(pJson.isMember("position"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["position"].isNull())
        {
            position_=std::make_shared<std::string>(pJson["position"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("priority"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["priority"].isNull())
        {
            priority_=std::make_shared<int32_t>((int32_t)pJson["priority"].asInt64());
        }
    }
}

void Committee::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            specialization_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            college_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            committee_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            profilePictureObjectKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            position_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            priority_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
}

void Committee::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("specialization"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["specialization"].isNull())
        {
            specialization_=std::make_shared<std::string>(pJson["specialization"].asString());
        }
    }
    if(pJson.isMember("college"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["college"].isNull())
        {
            college_=std::make_shared<std::string>(pJson["college"].asString());
        }
    }
    if(pJson.isMember("committee"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["committee"].isNull())
        {
            committee_=std::make_shared<std::string>(pJson["committee"].asString());
        }
    }
    if(pJson.isMember("profile_picture_object_key"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["profile_picture_object_key"].isNull())
        {
            profilePictureObjectKey_=std::make_shared<std::string>(pJson["profile_picture_object_key"].asString());
        }
    }
    if(pJson.isMember("position"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["position"].isNull())
        {
            position_=std::make_shared<std::string>(pJson["position"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("priority"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["priority"].isNull())
        {
            priority_=std::make_shared<int32_t>((int32_t)pJson["priority"].asInt64());
        }
    }
}

const int32_t &Committee::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Committee::getId() const noexcept
{
    return id_;
}
void Committee::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Committee::PrimaryKeyType & Committee::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Committee::getValueOfName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Committee::getName() const noexcept
{
    return name_;
}
void Committee::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Committee::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const std::string &Committee::getValueOfSpecialization() const noexcept
{
    const static std::string defaultValue = std::string();
    if(specialization_)
        return *specialization_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Committee::getSpecialization() const noexcept
{
    return specialization_;
}
void Committee::setSpecialization(const std::string &pSpecialization) noexcept
{
    specialization_ = std::make_shared<std::string>(pSpecialization);
    dirtyFlag_[2] = true;
}
void Committee::setSpecialization(std::string &&pSpecialization) noexcept
{
    specialization_ = std::make_shared<std::string>(std::move(pSpecialization));
    dirtyFlag_[2] = true;
}
void Committee::setSpecializationToNull() noexcept
{
    specialization_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Committee::getValueOfCollege() const noexcept
{
    const static std::string defaultValue = std::string();
    if(college_)
        return *college_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Committee::getCollege() const noexcept
{
    return college_;
}
void Committee::setCollege(const std::string &pCollege) noexcept
{
    college_ = std::make_shared<std::string>(pCollege);
    dirtyFlag_[3] = true;
}
void Committee::setCollege(std::string &&pCollege) noexcept
{
    college_ = std::make_shared<std::string>(std::move(pCollege));
    dirtyFlag_[3] = true;
}
void Committee::setCollegeToNull() noexcept
{
    college_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Committee::getValueOfCommittee() const noexcept
{
    const static std::string defaultValue = std::string();
    if(committee_)
        return *committee_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Committee::getCommittee() const noexcept
{
    return committee_;
}
void Committee::setCommittee(const std::string &pCommittee) noexcept
{
    committee_ = std::make_shared<std::string>(pCommittee);
    dirtyFlag_[4] = true;
}
void Committee::setCommittee(std::string &&pCommittee) noexcept
{
    committee_ = std::make_shared<std::string>(std::move(pCommittee));
    dirtyFlag_[4] = true;
}

const std::string &Committee::getValueOfProfilePictureObjectKey() const noexcept
{
    const static std::string defaultValue = std::string();
    if(profilePictureObjectKey_)
        return *profilePictureObjectKey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Committee::getProfilePictureObjectKey() const noexcept
{
    return profilePictureObjectKey_;
}
void Committee::setProfilePictureObjectKey(const std::string &pProfilePictureObjectKey) noexcept
{
    profilePictureObjectKey_ = std::make_shared<std::string>(pProfilePictureObjectKey);
    dirtyFlag_[5] = true;
}
void Committee::setProfilePictureObjectKey(std::string &&pProfilePictureObjectKey) noexcept
{
    profilePictureObjectKey_ = std::make_shared<std::string>(std::move(pProfilePictureObjectKey));
    dirtyFlag_[5] = true;
}
void Committee::setProfilePictureObjectKeyToNull() noexcept
{
    profilePictureObjectKey_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Committee::getValueOfPosition() const noexcept
{
    const static std::string defaultValue = std::string();
    if(position_)
        return *position_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Committee::getPosition() const noexcept
{
    return position_;
}
void Committee::setPosition(const std::string &pPosition) noexcept
{
    position_ = std::make_shared<std::string>(pPosition);
    dirtyFlag_[6] = true;
}
void Committee::setPosition(std::string &&pPosition) noexcept
{
    position_ = std::make_shared<std::string>(std::move(pPosition));
    dirtyFlag_[6] = true;
}
void Committee::setPositionToNull() noexcept
{
    position_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Committee::getValueOfDescription() const noexcept
{
    const static std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Committee::getDescription() const noexcept
{
    return description_;
}
void Committee::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[7] = true;
}
void Committee::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[7] = true;
}
void Committee::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[7] = true;
}

const int32_t &Committee::getValueOfPriority() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(priority_)
        return *priority_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Committee::getPriority() const noexcept
{
    return priority_;
}
void Committee::setPriority(const int32_t &pPriority) noexcept
{
    priority_ = std::make_shared<int32_t>(pPriority);
    dirtyFlag_[8] = true;
}
void Committee::setPriorityToNull() noexcept
{
    priority_.reset();
    dirtyFlag_[8] = true;
}

void Committee::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Committee::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "name",
        "specialization",
        "college",
        "committee",
        "profile_picture_object_key",
        "position",
        "description",
        "priority"
    };
    return inCols;
}

void Committee::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSpecialization())
        {
            binder << getValueOfSpecialization();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCollege())
        {
            binder << getValueOfCollege();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCommittee())
        {
            binder << getValueOfCommittee();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getProfilePictureObjectKey())
        {
            binder << getValueOfProfilePictureObjectKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPosition())
        {
            binder << getValueOfPosition();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getPriority())
        {
            binder << getValueOfPriority();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Committee::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Committee::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSpecialization())
        {
            binder << getValueOfSpecialization();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCollege())
        {
            binder << getValueOfCollege();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCommittee())
        {
            binder << getValueOfCommittee();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getProfilePictureObjectKey())
        {
            binder << getValueOfProfilePictureObjectKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPosition())
        {
            binder << getValueOfPosition();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getPriority())
        {
            binder << getValueOfPriority();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Committee::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getSpecialization())
    {
        ret["specialization"]=getValueOfSpecialization();
    }
    else
    {
        ret["specialization"]=Json::Value();
    }
    if(getCollege())
    {
        ret["college"]=getValueOfCollege();
    }
    else
    {
        ret["college"]=Json::Value();
    }
    if(getCommittee())
    {
        ret["committee"]=getValueOfCommittee();
    }
    else
    {
        ret["committee"]=Json::Value();
    }
    if(getProfilePictureObjectKey())
    {
        ret["profile_picture_object_key"]=getValueOfProfilePictureObjectKey();
    }
    else
    {
        ret["profile_picture_object_key"]=Json::Value();
    }
    if(getPosition())
    {
        ret["position"]=getValueOfPosition();
    }
    else
    {
        ret["position"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getPriority())
    {
        ret["priority"]=getValueOfPriority();
    }
    else
    {
        ret["priority"]=Json::Value();
    }
    return ret;
}

Json::Value Committee::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getSpecialization())
            {
                ret[pMasqueradingVector[2]]=getValueOfSpecialization();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCollege())
            {
                ret[pMasqueradingVector[3]]=getValueOfCollege();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCommittee())
            {
                ret[pMasqueradingVector[4]]=getValueOfCommittee();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getProfilePictureObjectKey())
            {
                ret[pMasqueradingVector[5]]=getValueOfProfilePictureObjectKey();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getPosition())
            {
                ret[pMasqueradingVector[6]]=getValueOfPosition();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[7]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getPriority())
            {
                ret[pMasqueradingVector[8]]=getValueOfPriority();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getSpecialization())
    {
        ret["specialization"]=getValueOfSpecialization();
    }
    else
    {
        ret["specialization"]=Json::Value();
    }
    if(getCollege())
    {
        ret["college"]=getValueOfCollege();
    }
    else
    {
        ret["college"]=Json::Value();
    }
    if(getCommittee())
    {
        ret["committee"]=getValueOfCommittee();
    }
    else
    {
        ret["committee"]=Json::Value();
    }
    if(getProfilePictureObjectKey())
    {
        ret["profile_picture_object_key"]=getValueOfProfilePictureObjectKey();
    }
    else
    {
        ret["profile_picture_object_key"]=Json::Value();
    }
    if(getPosition())
    {
        ret["position"]=getValueOfPosition();
    }
    else
    {
        ret["position"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getPriority())
    {
        ret["priority"]=getValueOfPriority();
    }
    else
    {
        ret["priority"]=Json::Value();
    }
    return ret;
}

bool Committee::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("specialization"))
    {
        if(!validJsonOfField(2, "specialization", pJson["specialization"], err, true))
            return false;
    }
    if(pJson.isMember("college"))
    {
        if(!validJsonOfField(3, "college", pJson["college"], err, true))
            return false;
    }
    if(pJson.isMember("committee"))
    {
        if(!validJsonOfField(4, "committee", pJson["committee"], err, true))
            return false;
    }
    else
    {
        err="The committee column cannot be null";
        return false;
    }
    if(pJson.isMember("profile_picture_object_key"))
    {
        if(!validJsonOfField(5, "profile_picture_object_key", pJson["profile_picture_object_key"], err, true))
            return false;
    }
    if(pJson.isMember("position"))
    {
        if(!validJsonOfField(6, "position", pJson["position"], err, true))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(7, "description", pJson["description"], err, true))
            return false;
    }
    if(pJson.isMember("priority"))
    {
        if(!validJsonOfField(8, "priority", pJson["priority"], err, true))
            return false;
    }
    return true;
}
bool Committee::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Committee::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("specialization"))
    {
        if(!validJsonOfField(2, "specialization", pJson["specialization"], err, false))
            return false;
    }
    if(pJson.isMember("college"))
    {
        if(!validJsonOfField(3, "college", pJson["college"], err, false))
            return false;
    }
    if(pJson.isMember("committee"))
    {
        if(!validJsonOfField(4, "committee", pJson["committee"], err, false))
            return false;
    }
    if(pJson.isMember("profile_picture_object_key"))
    {
        if(!validJsonOfField(5, "profile_picture_object_key", pJson["profile_picture_object_key"], err, false))
            return false;
    }
    if(pJson.isMember("position"))
    {
        if(!validJsonOfField(6, "position", pJson["position"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(7, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("priority"))
    {
        if(!validJsonOfField(8, "priority", pJson["priority"], err, false))
            return false;
    }
    return true;
}
bool Committee::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Committee::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
