/**
 *
 *  Committee.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Committee.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::icnari_conference_db;

const std::string Committee::primaryKeyName = "";
const bool Committee::hasPrimaryKey = false;
const std::string Committee::tableName = "committee";

const std::vector<typename Committee::MetaData> Committee::metaData_={
};
const std::string &Committee::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Committee::Committee(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Committee::Committee(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Committee::Committee(const Json::Value &pJson) noexcept(false)
{
}

void Committee::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void Committee::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Committee::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Committee::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Committee::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Committee::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Committee::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Committee::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value Committee::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Committee::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Committee::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Committee::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Committee::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Committee::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
