/**
 *
 *  Contact.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Contact.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::icnari_conference_db;

const std::string Contact::primaryKeyName = "";
const bool Contact::hasPrimaryKey = false;
const std::string Contact::tableName = "contact";

const std::vector<typename Contact::MetaData> Contact::metaData_={
};
const std::string &Contact::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Contact::Contact(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Contact::Contact(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Contact::Contact(const Json::Value &pJson) noexcept(false)
{
}

void Contact::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void Contact::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Contact::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Contact::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Contact::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Contact::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Contact::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Contact::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value Contact::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Contact::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Contact::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Contact::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Contact::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Contact::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
