/**
 *
 *  Notification.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Notification.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::icnari_conference_db;

const std::string Notification::primaryKeyName = "";
const bool Notification::hasPrimaryKey = false;
const std::string Notification::tableName = "notification";

const std::vector<typename Notification::MetaData> Notification::metaData_={
};
const std::string &Notification::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Notification::Notification(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 0 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
    }

}

Notification::Notification(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

Notification::Notification(const Json::Value &pJson) noexcept(false)
{
}

void Notification::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 0)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
}

void Notification::updateByJson(const Json::Value &pJson) noexcept(false)
{
}

void Notification::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Notification::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
    };
    return inCols;
}

void Notification::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
}

const std::vector<std::string> Notification::updateColumns() const
{
    std::vector<std::string> ret;
    return ret;
}

void Notification::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
}
Json::Value Notification::toJson() const
{
    Json::Value ret;
    return ret;
}

Json::Value Notification::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 0)
    {
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    return ret;
}

bool Notification::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Notification::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Notification::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    return true;
}
bool Notification::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 0)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Notification::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
