version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icnari27_app_container
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./config/:/app/config/:ro
    networks:
      - conference_network

networks:
  conference_network:
    driver: bridge