services:
  s3:
    image: soldevelo/minio:2026.7.17
    env_file:
      - s3.env
    ports:
      # Map the API port (for S3 clients)
      - "9000:9000"
      # Map the Console port (for the web UI)
      - "9001:9001"
    volumes:
      - ~/minio_data:/bitnami/minio/data
    # The command to start the MinIO server and enable the console
    
    command:
      - server
      - /bitnami/minio/data
      - --console-address
      - ":9001"
    networks:
      - conference_network
  
networks:
  conference_network:
    driver: bridge