const Registrations = () => {
  return (
    <div className="site-card w-full max-w-4xl mx-auto my-8 p-8">
      <section className="p-2 sm:p-4">
        <h2 className="text-3xl font-semibold mb-6 text-zinc-900 dark:text-slate-50 w-full text-center">Registration</h2>
        <p className="text-zinc-700 dark:text-slate-200 text-lg mb-6">To ensure inclusion in the final conference program for presentation and publication, authors must adhere to the following registration requirements:</p>
        <ul className="list-disc pl-6 text-zinc-700 dark:text-slate-200 text-lg">
          <li><strong className="font-semibold">✔ Mandatory Registration:</strong> At least one author (Main Author) of each accepted paper must complete the registration on or before the final registration deadline.</li>
          <li><strong className="font-semibold">✔ Paper Limit per Registration:</strong> Each full registration allows for the presentation and publication of manuscript. The manuscript must be between 5 to 7 pages in length.</li>
          <li><strong className="font-semibold">✔ For additional papers from same author:</strong>One registration covers up to two papers only. The second paper recieves a 50% discount. For more than two papers, authors must register again. Under each new registration, the second paper(4th, 6th, and so on) will also recieve a 50% discount </li>
          <li><strong className="font-semibold">✔ Payment Confirmation:</strong> Authors must retain a copy of their Transaction ID/UTR number generated by the payment gateway or bank. This will be required for payment verification and tracking.</li>
          <li><strong className="font-semibold">✔ Non-Refundable Fee:</strong> The registration fee is non-refundable under any circumstances.</li>
        </ul>
        <p className="text-zinc-700 dark:text-slate-200 mt-4 text-lg">For any queries regarding the registration process, please contact the conference secretariat or refer to the official conference website.</p>
        <h3 className="text-2xl font-semibold mt-6 text-zinc-900 dark:text-slate-50">Note: (Optional for Co-presenter registration)</h3>
        <ul className="list-disc pl-6 text-zinc-700 dark:text-slate-200 text-lg">
          <li><strong className="font-semibold">✔ Joint Presentation:</strong> Accepted paper authors may opt for a joint presentation. Both the main author and co-presenter must register separately to receive a presentation certificate.</li>
          <li><strong className="font-semibold">✔ Attendee Registration (Non-Author):</strong> Includes access to keynote sessions, panel discussions, and technical sessions. Papers will not be included in conference proceedings. A participation certificate will be provided upon successful registration.</li>
        </ul>
        <div className="container mx-auto px-0 sm:px-4 py-8 w-full overflow-x-auto mt-6">
          <h2 className="text-2xl sm:text-3xl font-bold mb-6 text-zinc-900 dark:text-slate-50">REGISTRATION FEE DETAILS (including GST)</h2>
          <table className="table-auto w-full border-collapse text-zinc-800 dark:text-slate-100">
            <thead className="bg-zinc-50 text-lg dark:bg-slate-900/40">
              <tr>
                <th className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60 text-left">Category</th>
                <th className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60 text-left">Early Registration<br />Before Date</th>
                <th className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60 text-left">Late Registration<br />After Date</th>
                <th className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60 text-left">Additional paper from same author</th>
              </tr>
            </thead>
            <tbody>
              <tr className="odd:bg-white even:bg-zinc-50 dark:odd:bg-slate-900/20 dark:even:bg-slate-900/40">
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">Students/Research Scholar</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">6500 INR</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">7500 INR</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">50% of registration amount</td>
              </tr>
              <tr className="odd:bg-white even:bg-zinc-50 dark:odd:bg-slate-900/20 dark:even:bg-slate-900/40">
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">Academicians</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">7500 INR</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">8500 INR</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">50% of registration amount</td>
              </tr>
              <tr className="odd:bg-white even:bg-zinc-50 dark:odd:bg-slate-900/20 dark:even:bg-slate-900/40">
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">Industry Participants</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">9000 INR</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">10000 INR</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">50% of registration amount</td>
              </tr>
              <tr className="odd:bg-white even:bg-zinc-50 dark:odd:bg-slate-900/20 dark:even:bg-slate-900/40">
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">Foreign Authors</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">250 USD</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">280 USD</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">50% of registration amount</td>
              </tr>
              <tr className="odd:bg-white even:bg-zinc-50 dark:odd:bg-slate-900/20 dark:even:bg-slate-900/40">
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">Accompanying Person</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">50% of registration amount</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60">50% of registration amount</td>
                <td className="px-6 py-3 border border-zinc-200 dark:border-slate-700/60 text-center">-----</td>
              </tr>
            </tbody>
          </table>
        </div>
         <div>
            <p className="text-zinc-700 dark:text-slate-200 mt-4 text-xl">Registration Fee for participants includes:</p>
            <ul className="list-disc pl-6 text-zinc-700 dark:text-slate-200 text-lg">
              <li>Entry to all the sessions of the conference and workshop</li>
              <li>Paper presentation/publication</li>
              <li>Certificate</li>
              <li>Registration Kit, High-Tea & Lunch (6th-8th March 2027), Gala dinner (7th March 2027) for participants attending physically</li>
            </ul>
          </div>
        <div className="mt-6">
          <h3 className="text-2xl font-semibold mb-3 text-zinc-900 dark:text-slate-50">Account Details</h3>
          <div className="space-y-4 text-lg text-zinc-700 dark:text-slate-200">
            <div>
              <strong className="font-semibold">Account Name:</strong> NIT Patna CF Account
            </div>
            <div>
              <strong className="font-semibold">Account Number:</strong> 50433562364
            </div>
            <div>
              <strong className="font-semibold">IFSC Code:</strong> IDIB000B810
            </div>
            <div>
              <strong className="font-semibold">Bank Name:</strong> Indian Bank
            </div>
            <div>
              <strong className="font-semibold">Branch:</strong> NIT Patna Campus
            </div>
            <div>
              <strong className="font-semibold">Complete Branch Address:</strong> Indian Bank, NIT Patna Campus, Ashok Rajpath, Patna, Bihar, PIN-800005
            </div>
            <div>
              <strong className="font-semibold">MICR Code:</strong> 800019027
            </div>
            <div>
              <strong className="font-semibold">Account Type:</strong> Savings 
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default Registrations
