#include<drogon/HttpAppFramework.h>
#include <aws/core/Aws.h>
#include"./utils/dotenv.hpp"
#include"./config/database.h"
using namespace drogon;

static void addCorsHeaders(const HttpRequestPtr &req, const HttpResponsePtr &resp)
{
    // Reflect the Origin when present (safer than '*' for some clients)
    const auto origin = req->getHeader("Origin");
    resp->addHeader("Access-Control-Allow-Origin", origin.empty() ? "*" : origin);
    resp->addHeader("Vary", "Origin");
    resp->addHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    resp->addHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    resp->addHeader("Access-Control-Max-Age", "86400");
}

int main(){
    Aws::SDKOptions awsOptions;
    Aws::InitAPI(awsOptions);

    Dotenv::load();
    const char* portEnv=std::getenv("PORT");
    app().loadConfigFile("./config/config.json");
    int port=3000;
    if (portEnv && *portEnv)
    {
        try
        {
            port = std::stoi(std::string(portEnv));
        }
        catch (const std::exception &e)
        {
            std::cerr << "Invalid PORT='" << portEnv << "' (" << e.what() << "); using " << port << "\n";
        }
    }
    else
    {
        std::cerr << "PORT not set (or .env missing); using " << port << "\n";
    }

    // Allow larger payloads (images, etc.)
    app().setClientMaxBodySize(50 * 1024 * 1024);
    app().setClientMaxMemoryBodySize(50 * 1024 * 1024);

    // CORS support
    app().registerPreRoutingAdvice([](
        const HttpRequestPtr &req, 
        std::function<void(const HttpResponsePtr &)> &&stop,
        std::function<void()> &&pass) {
        // Handle preflight OPTIONS requests
        if (req->method() == Options) {
            auto resp = HttpResponse::newHttpResponse();
            addCorsHeaders(req, resp);
            resp->setStatusCode(k204NoContent);
            stop(resp); // Send response and stop further processing
            return;
        }
        pass(); // Continue processing for non-OPTIONS requests
    });

    // Add CORS headers for all responses, including errors generated by Drogon (e.g. 413)
    app().registerPreSendingAdvice([](const HttpRequestPtr &req, const HttpResponsePtr &resp) {
        addCorsHeaders(req, resp);
    });
    auto threads = std::thread::hardware_concurrency();
    app().setThreadNum(threads);
    app().addListener("0.0.0.0",port);
    LOG_INFO << "=================================";
    LOG_INFO << "Starting Drogon Server";
    LOG_INFO << "Threads: " << threads;
    LOG_INFO << "Port: "<<port;
    LOG_INFO << "=================================";
    app().registerBeginningAdvice([]() {
        if (Database::isHealthy())
        {
            LOG_INFO << "Database connected successfully";
        }
        else
        {
            LOG_ERROR << "Database connection failed";
        }
    });
    app().run();

    Aws::ShutdownAPI(awsOptions);
    return 0;
}